### ISSUE TITLE
CI Test random failed

### ISSUE THREAD

**Issue by zmcNotafraid** [Magickbase/ckb-explorer-public-issues#710]
=== FAIL CkbSync::NodeDataProcessorTest#test_should_recalculate_udts_ckb_transactions_count_when_block_is_invalid_and_inputs_has_udt_cell (283.56s)
        Expected: 3
          Actual: 1
        test/models/ckb_sync/node_data_processor_test.rb:3770:in `block (2 levels) in <class:NodeDataProcessorTest>'
        test/models/ckb_sync/node_data_processor_test.rb:3765:in `block in <class:NodeDataProcessorTest>'

**Comment by zmcNotafraid** [comment]
contained_udt_ids were comment by [PR](https://github.com/nervosnetwork/ckb-explorer/commit/91563cc6b95d91a9e2caa1f3488fa40f79166ad8#diff-43d8e74cf1f6b77effa014acbe073983b6408419d11c711b89e6fc677b1a13ed). So it is not used any more.

**Comment by zmcNotafraid** [comment]
PR: https://github.com/nervosnetwork/ckb-explorer/pull/2015
